---
abstract: 'A collection of n-ary tree related modules'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Path::Class: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Forest
no_index:
  directory:
    - inc
    - t
requires:
  List::Util: 1.17
  Moose: 0.74
  MooseX::AttributeHelpers: 0.17
  MooseX::Clone: 0.05
  Scalar::Util: 1.17
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
