---
name: Forest
version: 0.01
author:
  - 'Stevan Little E<lt>stevan.little@iinteractive.comE<gt>'
abstract: nothing
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  JSON::Any: 1.15
  List::Util: 1.17
  Moose: 0.35
  MooseX::AttributeHelpers: 0.07
  Scalar::Util: 1.17
  Sub::Current: 0.02
build_requires:
  Test::Exception: 0.21
  Test::More: 0.47
provides:
  Forest:
    file: lib/Forest.pm
    version: 0.01
  Forest::Tree:
    file: lib/Forest/Tree.pm
    version: 0.01
  Forest::Tree::Indexer:
    file: lib/Forest/Tree/Indexer.pm
    version: 0.01
  Forest::Tree::Indexer::SimpleUIDIndexer:
    file: lib/Forest/Tree/Indexer/SimpleUIDIndexer.pm
    version: 0.01
  Forest::Tree::Reader:
    file: lib/Forest/Tree/Reader.pm
    version: 0.01
  Forest::Tree::Reader::SimpleTextFile:
    file: lib/Forest/Tree/Reader/SimpleTextFile.pm
    version: 0.01
  Forest::Tree::Roles::JSONable:
    file: lib/Forest/Tree/Roles/JSONable.pm
    version: 0.01
  Forest::Tree::Roles::MetaData:
    file: lib/Forest/Tree/Roles/MetaData.pm
    version: 0.01
  Forest::Tree::Service:
    file: lib/Forest/Tree/Service.pm
    version: 0.01
  Forest::Tree::Service::AJAX:
    file: lib/Forest/Tree/Service/AJAX.pm
    version: 0.01
  Forest::Tree::Writer:
    file: lib/Forest/Tree/Writer.pm
    version: 0.01
  Forest::Tree::Writer::SimpleASCII:
    file: lib/Forest/Tree/Writer/SimpleASCII.pm
    version: 0.01
  Forest::Tree::Writer::SimpleHTML:
    file: lib/Forest/Tree/Writer/SimpleHTML.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
